
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Astronomy'
tagline:          'from http://cnx.org/contents/LnN76Opl@10.13 (CC-BY)'
url:              https://github.com/philschatz/astronomy-book
origin:           http://cnx.org/contents/LnN76Opl@10.13

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          10.13

bookviewer:       http://philschatz.com/book-viewer

